name: Build Raymond
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup VS2019
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: Raymond
      run: msbuild Raymond.vcxproj /p:Configuration=Release /p:Platform=x64
